#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Australasian Genomes

# Short bio or description (displayed in the header)
description: Threatened Species Initiative and ARC Centre for Innovations in Peptides and Protein Science

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: /assets/images/TSI.png

# used in blog posts to denote the end of the excerpt used for lists
excerpt_separator: "<!--excerpt-->"


title: 
author: awgg-lab
email: soles.wildlife-genomics@sydney.edu.au
description: Genomic data repository for the Threatened Species Initiative and the ARC Centre for Innovations in Peptides and Protein Science

# social links
twitter_username: ThreatenedSpGen
twitter_username: ARC_CIPPS
github_username: awgg-lab

show_excerpts: true

theme: jekyll-theme-cayman

paginate: 6
paginate_path: "/news/page:num/"

collections:
  australasiangenomes:
    output: true
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: post
      comments: false
  -
    scope:
      path: "_species"
    values:
      layout: genomeark
      use_name_for_title: true
 
#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: awgg-lab
  instagram:
  linkedin:
  pinterest:
  rss: # uncomment and put something here to enable
  twitter: ThreatenedSpGen
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

grepository: tsi

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: tsi

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://github.com/awgg-lab/australasiangenomes

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - README.txt
  - CNAME
  - _statistics-cache/
  - _statistics-cache/*
  - _statistics-cache/*/*
  - _statistics-cache/*/*/*
  - _statistics-cache/*/*/*/*
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
