title: Australasian Genomes
author: awgg-lab
email: soles.wildlife-genomics@sydney.edu.au
description: Genomic data repository for the Threatened Species Initiative and the ARC Centre for Innovations in Peptides and Protein Science

# social links
twitter_username: ThreatenedSpGen
twitter_username: ARC_CIPPS
github_username: awgg-lab

show_excerpts: true

remote_theme: pages-themes/primer@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

